### ISSUE TITLE
Test pipeline fails on new version of the `coverage` package

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/hi-ml#125]
On Oct 3, coverage version 6.0 was released. Build pipeline worked fine until that date with version 5.5, but breaks with 6.0
Job link: https://github.com/microsoft/hi-ml/pull/124/checks?check_run_id=3791508427

**Comment by fepegar** [comment]
Shall we close this?

**Comment by ant0nsc** [comment]
Yup, it is not a blocker
