### ISSUE TITLE
Error during conversion of notebook to HTML

### ISSUE THREAD

**Issue by fepegar** [microsoft/hi-ml#263]
The error was raised in an InnerEye test: https://github.com/microsoft/InnerEye-DeepLearning/runs/5678939673?check_suite_focus=true#step:6:358

The InnerEye PR is
- https://github.com/microsoft/InnerEye-DeepLearning/pull/707

This is due to a recent release (two hours ago) of `jinja2`: https://github.com/pallets/jinja/releases/tag/3.1.0

The lower bound in the `hi-ml` includes the new version and that's causing the problem:
https://github.com/microsoft/hi-ml/blob/a108cf4ea244a76127adedc0ca60f0a5afdfb3e8/hi-ml/run_requirements.txt#L3

We probably need to add an upper bound for 3.1.0 as well.

Thanks @mebristo for investigating this.

**Comment by ant0nsc** [comment]
resolved by #266
