### ISSUE TITLE
Group all test runs in AzureML by PR number

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/hi-ml#271]
At present, we have the AzureML test runs that belong to a given PR scattered across experiments. It would be more helpful to have them grouped into one experiment

**Comment by vale-salvatelli** [comment]
Is this related to the fact now AzureML runs take the experiment name from the config? I think this is something we should change in general, it's more useful to have the experiment name connected to the branch/PR, not just for testing

**Comment by ant0nsc** [comment]
Resolved by #681
