### ISSUE TITLE
Add a max_run_duration flag for the GPU tests

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/hi-ml#309]
Similar to the flag max_run_duration in InnerEye, limit the runtime of the GPU test job to 30min

**Comment by ant0nsc** [comment]
* Add an additional commandline parameter max_run_duration in `hi-ml/run_pytest.py`
* Pass that through to the call to `submit_to_azure_if_needed`
* Set the timeout to 30min in the "Run GPU tests" step of the build pipeline

**Comment by kenza-bouzid** [comment]
Resolved in #319
