### ISSUE TITLE
Models that override  crossval_count with a value bigger than 1 automatically switch to train on AzureML even if user overrides --azureml=False

### ISSUE THREAD

**Issue by javier-alvarez** [microsoft/hi-ml#335]
Models that override  crossval_count with a value bigger than 1 automatically switch to train on AzureML even if user overrides --azureml=False

This behaviour is a bit confusing and I had to debug the code to understand what was happening. I would expect the runner to fail if there are contradicting parameters instead of overriding them for me and doing the opposite of what I want that is train locally.

Repro with:

/home/azureuser/hi-ml/hi-ml/src/health_ml/runner.py --model=histopathology.DeepSMILECrck 

Also the histopathology.DeepSMILECrck is not trainable because it does not have a default encoder type. Should we flag base classes as not trainable and throw an error?

**Comment by ant0nsc** [comment]
Resolved in #420
