### ISSUE TITLE
More info is needed on the behaviour of the pl_limit_batches flag 

### ISSUE THREAD

**Issue by mebristo** [microsoft/hi-ml#369]
It would be useful to have more information on the behaviour of the pl_limit_batches flag (i.e. pytorch lightning's fast_dev_run flag), e.g. describing that only a single epoch of training/ validation will run, and various callbacks are disabled. More info available [here](https://pytorch-lightning.readthedocs.io/en/stable/common/debugging.html#quick-unit-testing).

Perhaps we could add documentation in `docs/debugging.md` demonstrating a scenario in which this flag can be used to debug model training.

**Comment by ant0nsc** [comment]
@kenza-bouzid , In particular because callbacks are disabled, I would suggest to rename that flag to its corresponding name in PL, "--pl_fast_dev_run". With its present name, it suggests that it really does nothing beyond limiting the number of batches.
