### ISSUE TITLE
Jobs submitted in the histopathology folder should pick up the histo environment.yml file

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/hi-ml#393]
At present, they use the default `hi-ml` environment, and the actual environment needs to be specified via commandline args.

**Comment by ant0nsc** [comment]
@mebristo , can I have your thoughts on this one?

**Comment by mebristo** [comment]
I agree that a single environment definition is simpler (particularly for solving version clashes) but I think it would be even better if we could remove the additional command line arg altogether, and require the user to have an environment.yml file in the cwd. The major problem I can see here is that users who are not using hi-ml as a package will have to keep an eye out for changes to hi-ml's environment definition and update their own environment.yml, whereas with the current merging strategy they don't have to

**Comment by ant0nsc** [comment]
As discussed in person, we will keep a commandline option to specify a single environment file. If that is specified, use it. If not, try to find one in the current directory or upwards. Failing that, resort to the generic `hi-ml/environment.yml`.
We will keep on merging the pip requirements from hi-ml.
