### ISSUE TITLE
Retire the `--azureml` flag of the runner

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/hi-ml#394]
Everything that matters is the presence or absence of a cluster name. Once cluster name is given, it should run in AML.

**Comment by kenza-bouzid** [comment]
@ant0nsc @mebristo @vale-salvatelli @dccastro 
How do you feel about retiring this flag? This would mainly impact the hi-ml runner where sanity checks rely on this flag to validate the experiment. All if statements that involve `self.experiement_config.azureml ` will be replaced by `self.experiement_config.cluster`. Any thoughts?

**Comment by mebristo** [comment]
I see no issue with this

**Comment by kenza-bouzid** [comment]
About validate function in runner.py. We used to switch azureml on if hyperdrive or cross-val are turned on. Should we set the cluster to a "default" cluster available in the workspace (the first one for example)? Or rather raise an error and ask the user to set it?

**Comment by mebristo** [comment]
I think not, if the user has for example specified HyperDrive/ cross validation but hasn't specified a cluster, I think the appropriate behaviour would be to raise an Exception
