### ISSUE TITLE
Regression test results consume a lot of disk space

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/hi-ml#425]
Regression test results in the folder `hi-ml-histopathology` are huge, 140MB total. 
We can probably prune that by a lot by removing the last column that is the tile image path. Maybe even create a separate file with only slide-level output that can be compared more quickly.

**Comment by kenza-bouzid** [comment]
@mebristo can we close this? I believe it was already addressed in #418

**Comment by mebristo** [comment]
Yes we can close it thanks, the large files were removed here [#500 ](https://github.com/microsoft/hi-ml/pull/500)
