### ISSUE TITLE
URLs to multimodal documentation must be updated on Hugging Face

### ISSUE THREAD

**Issue by fepegar** [microsoft/hi-ml#459]
They currently point to the generic docs, but we now have docs for the multimodal toolbox.

**Comment by fepegar** [comment]
We should probably rename the symlink to the package description, as "https://hi-ml.readthedocs.io/en/latest/package_description_multimodal.html" is not a very nice URL.

@Shruthi42 @ozan-oktay

**Comment by Shruthi42** [comment]
The symlink to the multimodal folder/docs would also be useful when we update the [docs](https://huggingface.co/microsoft/BiomedVLP-CXR-BERT-specialized#further-information) on huggingface.

**Comment by fepegar** [comment]
Resolved in https://huggingface.co/microsoft/BiomedVLP-CXR-BERT-specialized/commit/b59c09e51ab2410b24f4be214bbb49043fe63fc2
