### ISSUE TITLE
Accept more prefixes for PR titles

### ISSUE THREAD

**Issue by fepegar** [microsoft/hi-ml#463]
Currently, we have the following:

https://github.com/microsoft/hi-ml/blob/c185873db4533f83d214f7303a2b5a3e426192c3/.github/workflows/check-pr-title.yml#L14

We might want to be more precise or accurate sometimes. I've seen others that could be useful. For example:

- `TEST`: to add or modify tests
- `FIX`: to fix something that is not necessarily a `BUG` such as a typo
- `MNT`: maintenance, to upgrade a package version (#453) or stuff related to packaging, linting, CI, etc.
- `STY`: as a shorter alternative to `STYLE`
- `REL`: for release commits
- `WIP`: for work in progress (I don't like this, I think using drafts PRs is better)
- `COMP`: fix e.g. warnings (I think it comes from "compiling" or similar)
- `PERF`: improve performance

Some sources:

- ITK: https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#commit-messages
- NiBabel: https://github.com/nipy/nibabel/commits/master

**Comment by Shruthi42** [comment]
Maybe we could have prefixes related to deprecating code as well. What is the recommended prefix for code deprecation PRs at the moment, `DEL`?

**Comment by fepegar** [comment]
> Maybe we could have prefixes related to deprecating code as well. What is the recommended prefix for code deprecation PRs at the moment, DEL?

I guess `DEL` would make sense for that, yes. These are all soft rules, anyway.

**Comment by ant0nsc** [comment]
`REL`, `COMP` don't really apply to us, I would drop those. And clearly no `WIP`. The others sound OK to me.

**Comment by fepegar** [comment]
Addressed in #505.
