### ISSUE TITLE
Change link in repository description

### ISSUE THREAD

**Issue by fepegar** [microsoft/hi-ml#473]
We currently have

<img alt="Screenshot 2022-06-28 162933" src="https://user-images.githubusercontent.com/12688084/176219637-56f4be6c-caef-46ab-bac1-a5050f74aee7.png">

I suggest we replace that with a short link to the docs, maybe https://hi-ml.rtfd.io/

At the moment, I think it's too hard to quickly find a link to the docs when one lands on the repo page.

**Comment by ant0nsc** [comment]
Done, now links to https://aka.ms/hi-ml

**Comment by fepegar** [comment]
Shall we change the description as well? Maybe "Microsoft Research Health ML toolbox"? It's the title of the first result when you Google "hi-ml".
