### ISSUE TITLE
Run tests in a conda environment for the histopathology workflow.

### ISSUE THREAD

**Issue by kenza-bouzid** [microsoft/hi-ml#479]
Run histopathology tests in a conda virtual environment instead of installing packages with pip.

**Comment by kenza-bouzid** [comment]
Reminder for @kenza-bouzid : add `pipdeptree --warn fail` action to the workflow

**Comment by kenza-bouzid** [comment]
We decided to not switch to conda env as it was too slow; can we close this? @ant0nsc

**Comment by ant0nsc** [comment]
Resolved by #478
