### ISSUE TITLE
Error running notebooks in CI 

### ISSUE THREAD

**Issue by fepegar** [microsoft/hi-ml#483]
Currently, in the multimodal CI,

1. The Jupyter notebook is run
1. In the first cell, the code from `main` is installed
1. If the PR introduces changes incompatible with `main`, an [error](https://github.com/microsoft/hi-ml/runs/7149265198?check_suite_focus=true) will be raised (as in #482)

The notebook should install the code in the PR, but that's not very nice for a demo notebook.

This could be solved [parameterizing the cell](https://papermill.readthedocs.io/en/latest/usage-parameterize.html) that installs the repo.

**Comment by Shruthi42** [comment]
Why do we need to install the package in the notebook? Shouldn't this be in written down in our setup instructions instead?

**Comment by fepegar** [comment]
I think it's best that the notebook can install all dependencies it needs, as is common practice for all demo notebooks.
