### ISSUE TITLE
Add support to compute embeddings and similarities

### ISSUE THREAD

**Issue by fepegar** [microsoft/hi-ml#604]
These functionalities are currently not trivial/well exposed for a new user. The following need to be modular and it needs to be crystal clear how to:

- Compute embeddings for an image
- Compute embeddings for a string
- Compute a similarity matrix for a number of embeddings

@ozan-oktay @Shruthi42

**Comment by ozan-oktay** [comment]
Closing the issue since it's addressed with #606
