### ISSUE TITLE
Jobs run out of disk space when run on Singularity

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/hi-ml#628]
On Singularity, many jobs fail somewhere in the middle because they exceed the amount of allocated scratch space. 

This can probably be worked around by setting environment variable `DATASET_MOUNT_CACHE_SIZE` to `300000000000` (300GB)

**Comment by kenza-bouzid** [comment]
Seems like this is solved. Can we close it? @ant0nsc

**Comment by ant0nsc** [comment]
Yes, this can be closed - this is an issue only for amulet, and there we set env variables in the config file.
