### ISSUE TITLE
MockHistoDataGenerator generates corrupted tiff files

### ISSUE THREAD

**Issue by kenza-bouzid** [microsoft/hi-ml#716]
Update tiffwriter arguments after upgrade in #691

**Comment by ant0nsc** [comment]
:-O In how far are the tiff files corrupted?

**Comment by kenza-bouzid** [comment]
It's not a blocking one. I just saw the same warning slow-path while debugging some tests, so I'll need to update the params of TiffWriter as we did for conversion
