### ISSUE TITLE
Fix intermittently failing dataset tests

### ISSUE THREAD

**Issue by mebristo** [microsoft/hi-ml#74]
AML Dataset's get_by_name sometimes returns ServiceException 204 - 'unknown error'

Examples of failed runs:
- https://github.com/microsoft/hi-ml/runs/3342537508?check_suite_focus=true
- https://github.com/microsoft/hi-ml/runs/3349433791?check_suite_focus=true

**Comment by JonathanTripp** [comment]
This also failed:

https://github.com/microsoft/hi-ml/runs/3374648332?check_suite_focus=true

this was calling:

```
    # Delete the dataset again
    dataset2.unregister_all_versions()
```

in the test: test_get_dataset()

**Comment by JonathanTripp** [comment]
https://github.com/microsoft/hi-ml/runs/3349433791?check_suite_focus=true

failure is in

```
    existing_dataset.unregister_all_versions()
```

in the test : test_get_dataset()
