### ISSUE TITLE
CI fails: "pages build and deployment"

### ISSUE THREAD

**Issue by fepegar** [microsoft/hi-ml#825]
Example: https://github.com/microsoft/hi-ml/actions/runs/4315342706/jobs/7529588939

It happens because of this line, @ant0nsc.

https://github.com/microsoft/hi-ml/blob/06acc07f12e8e5c7a83441291e719ee57397524c/docs/source/histoqc.md?plain=1#L12

**Comment by ant0nsc** [comment]
Verified that the `pages` build is now green @fepegar
