### ISSUE TITLE
Availability of ResNets aligned with CXR-BERT, trained on MIMIC-CXR

### ISSUE THREAD

**Issue by marcomistretta** [microsoft/hi-ml#832]
Dear @fepegar and hi-ml team,

I am writing to inquire about the availability of
ResNet-18 and ResNet-50 of Model **BioViL ** that have been aligned with
CXR-BERT trainining on MIMIC-CXR. 

I came across the Hi-ML-Multimodal documentation and found
instructions on how to download the pretrained text transformer, but I
was unable to find any information regarding the pretrained vision
encoders.

I was wondering if you could please let me know if these vision encoders trained on MIMIC-CXR are available for download, and if so, where I can find them. 

Any information you can provide would be greatly
appreciated.

Thank you very much for your time and consideration

**Comment by fepegar** [comment]
Hi, @marcomistretta. Have you tried the following?

```python
from health_multimodal.image import get_biovil_resnet
encoder = get_biovil_resnet()
```

**Comment by fepegar** [comment]
No worries. Feel free to suggest improvements to the documentation!
