### ISSUE TITLE
Please fix "pip install hi-ml-multimodal" or use my fork for a working version

### ISSUE THREAD

**Issue by NamanSharma5** [microsoft/hi-ml#916]

**Comment by NamanSharma5** [comment]
Hi @Shruthi42, @corcra and the wider BioViL-T team. Thank you for open sourcing this repo and the corresponding weights for the BioVil-T model! 

Unfortunately your Python package "hi-ml-multimodal 0.2.1" on the Python Package Index has an issue when being installed.

This is because of the use of **non-existent versions of dependencies**, namely _SimpleITK=2.1.1_ and the **use of deprecated functions**, specifically  _torch_int_div_ from _transformers==4.17.0_ and _model_urls_ from _torchvision.models.resnet_ in torchvision==0.12.0.

**Comment by NamanSharma5** [comment]
As a temporary fix, I have setup a fork with an updated requirements.txt containing an older version of the torchvision and transformers to support the Hi-Ml-Multimodal codebase - this can be viewed on my GitHub,

**Comment by yunyiliu** [comment]
still not fixed yet, the problem of pip install hi-ml-multimodal still here, can you please fix it

**Comment by fepegar** [comment]
Things should work after this is merged:

- https://github.com/microsoft/hi-ml/pull/928/
