### ISSUE TITLE
Finetuning on report generation task

### ISSUE THREAD

**Issue by Markin-Wang** [microsoft/hi-ml#935]
Hi, thank you for your work and code.

In the paper, the proposed framework was verified on the report generation task.

However, it seems that no relevant script/guideline or codes for this part in the repo.

Could you provide any guideline for this? Thank you for your help.

**Comment by fepegar** [comment]
@corcra @Shruthi42

**Comment by fepegar** [comment]
Hi @Markin-Wang. Unfortunately, we're not planning to release any code for report generation training.
